BOOKS =[
    "312 Ways To Die",
    "24 Hours to Code : no sleep",
    "A Great Plenty",
    "A la recherche du temps perdu",
    "A Stitch In Time",
    "A Trip To The Dentist",
    "A review : 7 Ways To Kill Yourself With Shampoo",
    "A Whole Lot Of Cats",
    "Acrophobia Explained",
    "Advanced Math",
    "After The Corned Beef And Cabbage",
    "Ah, Thor!",
    "All Different Ways To Spell Bob",
    "All-You-Can-Eat Buffets",
    "Allegiance To The King",
    "Almost Missed The Bus",
    "Ambulance Driving",
    "Ambush!",
    "And Shut Up!",
    "And The Other People",
    "Animal Illness",
    "Animal Scents",
    "Answering the Questions of the Universe",
    "Antlers In The Tree Top",
    "April Fool!",
    "Archery",
    "Are We There Yet?",
    "Armed Heists",
    "Artificial Clothing",
    "Artificial Weightlessness",
    "As Solid As",
    "Assault With Battery",
    "At The Bottom Of The Can",
    "Athletic Supporter",
    "Attractive Floral Arrangements",
    "Back Row Of The Orchestra",
    "Bad Cow Joe-ks",
    "Bad Falls",
    "Bad Gardeners",
    "Bad Investments",
    "Banquet At McDonalds",
    "Baseball",
    "Baseball Poetry",
    "Bathroom Etiquette",
    "Battle Axes",
    "Be Prepared",
    "Beach Blanket Bingo",
    "Beach Rides",
    "Bedtime",
    "Beekeeping",
    "Bestiary of Plant Eaters",
    "Big Fart",
    "Blonde Hair",
    "Blowout!",
    "Board Game Challenge",
    "Body Parts",
    "Boring Midwestern Cities",
    "Boxing Cornerman’s Story",
    "Boy Scout’s Handbook",
    "Brain Surgery",
    "Breaking The La    wBring o The Grocer’s",
    "Broken Window",
    "Brown Stains on the Wall",
    "Bubbles In The Bathtub",
    "Cab Calloway’sGarden",
    "Canadian Religion",
    "Candle-Vaulting",
    "Car Capital Of The World",
    "Car Repair sCare For A Chop?",
    "Career Opportunities for History Majors",
    "Carnival Rides",
    "Carpet Fitting",
    "Caulking Made Easy",
    "Chauvinistic Men",
    "Cheap Transmissions",
    "Cheaper Than IBM",
    "Cheating On His Wife",
    "Chest Pai  nChicago Gangs Of The 30’s",
    "Chicken Dishes",
    "Children’s Songbook",
    "Chinese Apathy",
    "Chinese Gold Rush",
    "Chinese Meals On Wheels",
    "Chinese Toy Recalls",
    "Christmas for Baldies",
    "Circle Perimeter",
    "Classic Groceries",
    "Clear Sky Forecast",
    "Cloning",
    "Clothes For Germ Kings",
    "College Athletics",
    "Come On In!",
    "Columbus, Vespucci And Me",
    "Computer Memories",
    "Confessions Of A Gold Digger",
    "Cooking A Turkey",
    "Cooking Spaghetti",
    "Cosmetology",
    "Covered Walkways",
    "Crack in the Sidewalk",
    "Crackdown",
    "Credit Cards",
    "Crocodile Dundee",
    "Cry Wolf",
    "Cut the Grass  !Daddy, Are We There Yet?",
    "Dance The Night Away",
    "Danger!",
    "Dangerous Animals",
    "Dealing With Skunks",
    "Decorating Your Mousehole",
    "Defunct Nations",
    "Dentist Appointment",
    "Desert Crossing",
    "Desert Storm Approaches",
    "Dieting",
    "Dinner Delight",
    "Dirty Chinese Windows",
    "Dive! Dive !",
    "Do I Look Fat?",
    "Do It Yourself",
    "Do You Hear a Phone",
    "Don’t Come Back Again",
    "Don’t Do Anything Rash",
    "Don’t Tread On Me",
    "Downpour",
    "Drafted",
    "Dragonslayer",
    "Drinking Problems",
    "Drops on the Toilet Seat",
    "Dull Razor",
    "East Coast Resorts",
    "East Coast Universities",
    "Eating Disorders",
    "Ecclesiastical Infractions",
    "Embarrassed In The Shower",
    "Empathy",
    "Employment Handbook",
    "En Garde!",
    "Equine Leg Cramps",
    "Erotic Adventures",
    "Errors and Accidents",
    "Events In The Soviet Union",
    "Exercise On Wheels",
    "Exotic Irish Plants",
    "Explaining It Better",
    "Exploring Haunted Houses",
    "Exploring The Dutch Frontier",
    "Ex-Presidential Retreat",
    "Extreme Hair Makeover",
    "Fairy Fantasy World",
    "Fallen Underwear",
    "Falling Off A Bridge",
    "Falling On Your Head",
    "Falling Trees",
    "Famous Philosophers",
    "Fastest Gun In The West",
    "Fat Lady In The Sideshow",
    "Feelings",
    "Fifty Yards To The Outhouse",
    "Fifty Years In The Saddle",
    "Financial Insecurity",
    "Fingerplay",
    "Fix Your Car!",
    "Fish Story",
    "Fixing Computer Programs",
    "Flips And Tumbles",
    "Flogging In The Army",
    "Fluffy Pillows",
    "Foot Coverings",
    "Foot Problems of Big Lumberjacks",
    "Fortune Telling",
    "Fred Can Philosophize",
    "Free Willy",
    "French Cars",
    "French Hospitality",
    "French Overpopulation",
    "Frisbee",
    "Full Moon",
    "Galaxy Wars",
    "Gambling",
    "Gangway!",
    "Gardening With The Ex-President",
    "Genie In A Bottle",
    "Get Moving!",
    "Get Out There!",
    "Girl On a Budget",
    "Glass Bikini",
    "Glue",
    "Go Away!",
    "Goes",
    "Golly Gosh!",
    "Gone Fishing",
    "Gone With The Wind",
    "Good Housekeeping",
    "Good Steak",
    "Good Works",
    "Gotta Go To The Bathroom",
    "Grave Mistakes",
    "Great Mysteries",
    "Great Resturants",
    "Great Tennis Matches",
    "Greek Unbeliever",
    "Green Lawn Chairs",
    "Green Spot On The Wall",
    "Greenhouse Flowers",
    "Greeting Sheep Strangers",
    "Growing up in the Balkans",
    "Guarding the Door",
    "Guide To Mixology",
    "Gunslingers With Gas",
    "Gut-Busting Rides"
]
